import {
  Tournament,
  User,
  Team,
  Match,
  Registration,
  MatchResult,
  UserWallet,
  WalletLedgerItem,
  WithdrawalRequest,
  SupportTicket,
  AppNotification,
  AuditLog,
  SystemSettings,
  LeaderboardEntry
} from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-phoenix',
    fullName: 'Rohan Sharma',
    username: 'Phoenix_FF',
    email: 'rohan.sharma@esports.io',
    mobile: '+91 98765 43210',
    role: 'USER',
    playerUid: 'FF-89241031',
    ign: 'Phoenix_99',
    avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-11-12T10:00:00Z',
    teamId: 'team-vortex',
    status: 'ACTIVE',
    stats: {
      totalMatches: 42,
      wins: 8,
      winRate: 19.05,
      totalEarnings: 8500,
      kills: 148,
      kdRatio: 4.35,
    },
    achievements: [
      {
        id: 'ach-1',
        title: 'First Blood & Win',
        description: 'Secured Booyah with 10+ squad kills in official tournament',
        icon: 'Crown',
        unlockedAt: '2025-12-05T18:30:00Z',
      },
      {
        id: 'ach-2',
        title: 'Champion of Bermuda',
        description: '1st place finish in Bermuda Clash Season 4',
        icon: 'Trophy',
        unlockedAt: '2026-01-14T20:00:00Z',
      },
      {
        id: 'ach-3',
        title: 'Top Fragger',
        description: 'Awarded MVP Fragger with 14 kills in a single match',
        icon: 'Flame',
        unlockedAt: '2026-02-10T19:00:00Z',
      },
      {
        id: 'ach-4',
        title: 'Winning Streak',
        description: 'Won 3 consecutive tournament matches',
        icon: 'Zap',
        unlockedAt: '2026-03-01T21:15:00Z',
      },
      {
        id: 'ach-5',
        title: 'Tournament Veteran',
        description: 'Participated in more than 20 sanctioned events',
        icon: 'Shield',
        unlockedAt: '2026-05-18T16:00:00Z',
      },
    ],
  },
  {
    id: 'user-frostbyte',
    fullName: 'Aryan Verma',
    username: 'FrostByte',
    email: 'aryan.verma@esports.io',
    mobile: '+91 98111 22334',
    role: 'USER',
    playerUid: 'FF-77192844',
    ign: 'FrostByte_Cap',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-10-01T08:00:00Z',
    teamId: 'team-vortex',
    status: 'ACTIVE',
    stats: {
      totalMatches: 65,
      wins: 15,
      winRate: 23.07,
      totalEarnings: 14200,
      kills: 220,
      kdRatio: 4.88,
    },
    achievements: [],
  },
  {
    id: 'user-admin',
    fullName: 'Vikramaditya Rao',
    username: 'Apex_Operator',
    email: 'admin@freefiretournaments.pro',
    mobile: '+91 99999 88888',
    role: 'SUPER_ADMIN',
    playerUid: 'FF-ADMIN-001',
    ign: 'OP_Commander',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-01-01T00:00:00Z',
    status: 'ACTIVE',
    stats: {
      totalMatches: 0,
      wins: 0,
      winRate: 0,
      totalEarnings: 0,
      kills: 0,
      kdRatio: 0,
    },
    achievements: [],
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-vortex',
    name: 'VORTEX ESPORTS',
    tag: 'VRX',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    captainId: 'user-phoenix',
    matchesPlayed: 42,
    wins: 12,
    totalEarnings: 22500,
    createdAt: '2025-11-15T12:00:00Z',
    members: [
      {
        userId: 'user-phoenix',
        username: 'Phoenix_FF',
        ign: 'Phoenix_99',
        playerUid: 'FF-89241031',
        role: 'CAPTAIN',
        joinedAt: '2025-11-15T12:00:00Z',
      },
      {
        userId: 'user-frostbyte',
        username: 'FrostByte',
        ign: 'FrostByte_Cap',
        playerUid: 'FF-77192844',
        role: 'MEMBER',
        joinedAt: '2025-11-16T15:00:00Z',
      },
      {
        userId: 'user-shadow',
        username: 'ShadowRogue',
        ign: 'Shadow_Ninja',
        playerUid: 'FF-66381029',
        role: 'MEMBER',
        joinedAt: '2025-11-20T18:00:00Z',
      },
      {
        userId: 'user-blaze',
        username: 'BlazeStriker',
        ign: 'Blaze_Sniper',
        playerUid: 'FF-55492018',
        role: 'MEMBER',
        joinedAt: '2025-11-22T10:00:00Z',
      },
    ],
  },
  {
    id: 'team-soulfire',
    name: 'SOUL FIRE GAMING',
    tag: 'SFG',
    logo: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=150&auto=format&fit=crop&q=80',
    captainId: 'user-soul1',
    matchesPlayed: 56,
    wins: 18,
    totalEarnings: 38000,
    createdAt: '2025-10-10T12:00:00Z',
    members: [
      {
        userId: 'user-soul1',
        username: 'SoulMortal',
        ign: 'SFG_Mortal',
        playerUid: 'FF-44112233',
        role: 'CAPTAIN',
        joinedAt: '2025-10-10T12:00:00Z',
      },
      {
        userId: 'user-soul2',
        username: 'SoulViper',
        ign: 'SFG_Viper',
        playerUid: 'FF-44112234',
        role: 'MEMBER',
        joinedAt: '2025-10-10T12:00:00Z',
      },
    ],
  },
  {
    id: 'team-godlike',
    name: 'GODLIKE FF',
    tag: 'GDL',
    logo: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=150&auto=format&fit=crop&q=80',
    captainId: 'user-god1',
    matchesPlayed: 70,
    wins: 24,
    totalEarnings: 52000,
    createdAt: '2025-09-01T12:00:00Z',
    members: [
      {
        userId: 'user-god1',
        username: 'Neyoo_FF',
        ign: 'GDL_Neyoo',
        playerUid: 'FF-99887766',
        role: 'CAPTAIN',
        joinedAt: '2025-09-01T12:00:00Z',
      },
    ],
  },
];

export const INITIAL_TOURNAMENTS: Tournament[] = [
  {
    id: 'tourn-1',
    slug: 'free-fire-battle-arena-s6',
    name: 'FREE FIRE BATTLE ARENA — S6',
    description: 'The flagship premier squad championship of Free Fire. Battle across classic Bermuda for glory, leaderboard points, and cash prizes.',
    banner: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80',
    game: 'Free Fire',
    mode: 'Squad',
    map: 'Bermuda',
    perspective: 'TPP',
    teamSize: 4,
    entryFee: 50,
    prizePool: 10000,
    prizes: [
      { rank: 1, label: '1st Place (Champion)', amount: 5000 },
      { rank: 2, label: '2nd Place (Runner-up)', amount: 3000 },
      { rank: 3, label: '3rd Place', amount: 1500 },
      { rank: 4, label: '4th Place', amount: 500 },
    ],
    maxSlots: 48,
    joinedSlots: 42,
    status: 'LIVE',
    registrationStart: '2026-09-01T10:00:00Z',
    registrationEnd: '2026-09-10T17:00:00Z',
    tournamentStart: '2026-09-10T18:00:00Z',
    matchCount: 3,
    scoringRules: {
      placementPoints: { 1: 15, 2: 12, 3: 10, 4: 8, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoints: 2,
      bonusPoints: 3,
      penalties: 0,
      tieBreakRule: 'Most Kills, then Placement in Final Match',
    },
    rules: [
      'Emulators, iPads/tablets, and third-party aim assists are strictly prohibited.',
      'All players must be at level 40+ in Free Fire with verified in-game UID.',
      'Team captains must submit full-screen post-match screenshots within 15 minutes of match completion.',
      'Teaming or ungentlemanly conduct will result in immediate disqualification and wallet forfeiture.',
      'Room ID and Password will be visible 15 minutes prior to match start in the Match Room tab.',
    ],
    schedule: [
      { phase: 'Registration Open', timestamp: '2026-09-01T10:00:00Z', completed: true },
      { phase: 'Registration Closed', timestamp: '2026-09-10T17:00:00Z', completed: true },
      { phase: 'Room Details Released', timestamp: '2026-09-10T17:45:00Z', completed: true },
      { phase: 'Match Started', timestamp: '2026-09-10T18:00:00Z', completed: true },
      { phase: 'Results Verification', timestamp: '2026-09-10T19:00:00Z', completed: false },
      { phase: 'Prize Distribution', timestamp: '2026-09-10T19:30:00Z', completed: false },
    ],
    createdAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'tourn-2',
    slug: 'bermuda-clash-championship',
    name: 'BERMUDA CLASH PRO CHAMPIONSHIP',
    description: 'High-stakes battle royale competition with amplified kill multipliers. Prove your squad’s tactical dominance.',
    banner: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80',
    game: 'Free Fire',
    mode: 'Squad',
    map: 'Bermuda',
    perspective: 'TPP',
    teamSize: 4,
    entryFee: 100,
    prizePool: 25000,
    prizes: [
      { rank: 1, label: '1st Place', amount: 12000 },
      { rank: 2, label: '2nd Place', amount: 7000 },
      { rank: 3, label: '3rd Place', amount: 4000 },
      { rank: 4, label: '4th Place', amount: 2000 },
    ],
    maxSlots: 48,
    joinedSlots: 38,
    status: 'REGISTRATION_OPEN',
    registrationStart: '2026-09-05T12:00:00Z',
    registrationEnd: '2026-09-11T18:00:00Z',
    tournamentStart: '2026-09-11T20:00:00Z',
    matchCount: 4,
    scoringRules: {
      placementPoints: { 1: 15, 2: 12, 3: 10, 4: 8, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoints: 2,
      bonusPoints: 0,
      penalties: 0,
      tieBreakRule: 'Total Kill Points, then Highest Placement',
    },
    rules: [
      'Standard esports tournament rules apply. No gun attributes or characters with overpowered passive heals.',
      'Every team member must be registered on the roster prior to registration close.',
      'In case of server disconnection by Garena, a rematch will be scheduled if >20 players disconnect before the first safe zone shrinks.',
    ],
    schedule: [
      { phase: 'Registration Open', timestamp: '2026-09-05T12:00:00Z', completed: true },
      { phase: 'Registration Closed', timestamp: '2026-09-11T18:00:00Z', completed: false },
      { phase: 'Room Details Released', timestamp: '2026-09-11T19:45:00Z', completed: false },
      { phase: 'Match Started', timestamp: '2026-09-11T20:00:00Z', completed: false },
      { phase: 'Prize Distribution', timestamp: '2026-09-11T22:00:00Z', completed: false },
    ],
    createdAt: '2026-09-02T14:00:00Z',
  },
  {
    id: 'tourn-3',
    slug: 'solo-night-hunter-cup',
    name: 'SOLO NIGHT HUNTER CUP [FREE ENTRY]',
    description: 'Free-to-enter solo clash on the desert dunes of Kalahari. Top fraggers take home instant cash rewards.',
    banner: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&auto=format&fit=crop&q=80',
    game: 'Free Fire',
    mode: 'Solo',
    map: 'Kalahari',
    perspective: 'TPP',
    teamSize: 1,
    entryFee: 0,
    prizePool: 5000,
    prizes: [
      { rank: 1, label: '1st Place', amount: 2500 },
      { rank: 2, label: '2nd Place', amount: 1500 },
      { rank: 3, label: '3rd Place', amount: 700 },
      { rank: 4, label: '4th Place', amount: 300 },
    ],
    maxSlots: 100,
    joinedSlots: 96,
    status: 'REGISTRATION_OPEN',
    registrationStart: '2026-09-08T09:00:00Z',
    registrationEnd: '2026-09-10T21:00:00Z',
    tournamentStart: '2026-09-10T22:00:00Z',
    matchCount: 2,
    scoringRules: {
      placementPoints: { 1: 20, 2: 15, 3: 12, 4: 10, 5: 8, 6: 6, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoints: 1,
      bonusPoints: 0,
      penalties: 0,
      tieBreakRule: 'Most Kills in Match 2',
    },
    rules: [
      'Solo entry only. Teaming or sharing vehicles will lead to an immediate ban.',
      'Evidence screenshot must clearly show your player UID and match kill counter.',
    ],
    schedule: [
      { phase: 'Registration Open', timestamp: '2026-09-08T09:00:00Z', completed: true },
      { phase: 'Registration Closed', timestamp: '2026-09-10T21:00:00Z', completed: false },
      { phase: 'Match Started', timestamp: '2026-09-10T22:00:00Z', completed: false },
    ],
    createdAt: '2026-09-08T09:00:00Z',
  },
  {
    id: 'tourn-4',
    slug: 'duo-purgatory-showdown',
    name: 'DUO PURGATORY SHOWDOWN',
    description: 'Dynamic duo skirmish through the treacherous valleys of Purgatory. Coordinated communication is key.',
    banner: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    game: 'Free Fire',
    mode: 'Duo',
    map: 'Purgatory',
    perspective: 'TPP',
    teamSize: 2,
    entryFee: 40,
    prizePool: 8000,
    prizes: [
      { rank: 1, label: '1st Place', amount: 4000 },
      { rank: 2, label: '2nd Place', amount: 2500 },
      { rank: 3, label: '3rd Place', amount: 1500 },
    ],
    maxSlots: 24,
    joinedSlots: 24,
    status: 'REGISTRATION_CLOSED',
    registrationStart: '2026-09-06T10:00:00Z',
    registrationEnd: '2026-09-10T12:00:00Z',
    tournamentStart: '2026-09-10T19:30:00Z',
    matchCount: 2,
    scoringRules: {
      placementPoints: { 1: 15, 2: 12, 3: 10, 4: 8, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoints: 2,
      bonusPoints: 0,
      penalties: 0,
      tieBreakRule: 'Total Kill Points',
    },
    rules: [
      'Both players in the duo must be in the same lobby.',
      'Substitutes must be declared before registration closure.',
    ],
    schedule: [
      { phase: 'Registration Closed', timestamp: '2026-09-10T12:00:00Z', completed: true },
      { phase: 'Match Started', timestamp: '2026-09-10T19:30:00Z', completed: false },
    ],
    createdAt: '2026-09-05T10:00:00Z',
  },
  {
    id: 'tourn-5',
    slug: 'nexterra-cyber-clash',
    name: 'NEXTERRA CYBER CLASH INVITATIONAL',
    description: 'High-octane battles in the futuristic arena of NexTerra with zero-gravity zones and jump pads.',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
    game: 'Free Fire',
    mode: 'Squad',
    map: 'NexTerra',
    perspective: 'TPP',
    teamSize: 4,
    entryFee: 150,
    prizePool: 50000,
    prizes: [
      { rank: 1, label: '1st Place', amount: 25000 },
      { rank: 2, label: '2nd Place', amount: 15000 },
      { rank: 3, label: '3rd Place', amount: 7000 },
      { rank: 4, label: '4th Place', amount: 3000 },
    ],
    maxSlots: 48,
    joinedSlots: 12,
    status: 'UPCOMING',
    registrationStart: '2026-09-12T10:00:00Z',
    registrationEnd: '2026-09-18T18:00:00Z',
    tournamentStart: '2026-09-19T18:00:00Z',
    matchCount: 5,
    scoringRules: {
      placementPoints: { 1: 15, 2: 12, 3: 10, 4: 8, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoints: 2,
      bonusPoints: 5,
      penalties: 0,
      tieBreakRule: 'Most Booyahs, then Total Kills',
    },
    rules: [
      'Official pro-tier tournament rules.',
      'Live stream delay of 3 minutes is mandatory for all co-streamers.',
    ],
    schedule: [
      { phase: 'Registration Opens Soon', timestamp: '2026-09-12T10:00:00Z', completed: false },
    ],
    createdAt: '2026-09-07T11:00:00Z',
  },
  {
    id: 'tourn-6',
    slug: 'alpine-pro-scrims-s5',
    name: 'ALPINE PRO SCRIMS — S5',
    description: 'Weekly competitive scrim series on Alpine snowy peaks. Completed season with verified standings.',
    banner: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=1200&auto=format&fit=crop&q=80',
    game: 'Free Fire',
    mode: 'Squad',
    map: 'Alpine',
    perspective: 'TPP',
    teamSize: 4,
    entryFee: 20,
    prizePool: 4000,
    prizes: [
      { rank: 1, label: '1st Place', amount: 2500 },
      { rank: 2, label: '2nd Place', amount: 1500 },
    ],
    maxSlots: 48,
    joinedSlots: 48,
    status: 'COMPLETED',
    registrationStart: '2026-08-20T10:00:00Z',
    registrationEnd: '2026-08-27T18:00:00Z',
    tournamentStart: '2026-08-28T19:00:00Z',
    matchCount: 3,
    scoringRules: {
      placementPoints: { 1: 15, 2: 12, 3: 10, 4: 8, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoints: 1,
      bonusPoints: 0,
      penalties: 0,
      tieBreakRule: 'Placement Points',
    },
    rules: ['Scored by official Free Fire point matrix.'],
    schedule: [
      { phase: 'Tournament Completed', timestamp: '2026-08-28T22:00:00Z', completed: true },
      { phase: 'Prizes Paid Out', timestamp: '2026-08-28T23:00:00Z', completed: true },
    ],
    createdAt: '2026-08-15T12:00:00Z',
  },
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'match-101',
    tournamentId: 'tourn-1',
    matchNumber: 1,
    map: 'Bermuda',
    startTime: '2026-09-10T18:00:00Z',
    status: 'LIVE',
    roomId: '6582049',
    password: 'FF#PRO88',
    credentialsReleased: true,
    instructions: 'Enter custom room with your designated slot number (Slot #14 for VORTEX ESPORTS). Match launches strictly at 18:00 sharp.',
  },
  {
    id: 'match-102',
    tournamentId: 'tourn-1',
    matchNumber: 2,
    map: 'Purgatory',
    startTime: '2026-09-10T18:45:00Z',
    status: 'SCHEDULED',
    credentialsReleased: false,
    instructions: 'Room details will unlock automatically 10 minutes prior to match time.',
  },
  {
    id: 'match-103',
    tournamentId: 'tourn-1',
    matchNumber: 3,
    map: 'Kalahari',
    startTime: '2026-09-10T19:30:00Z',
    status: 'SCHEDULED',
    credentialsReleased: false,
    instructions: 'Final championship decider match.',
  },
];

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    id: 'reg-1',
    tournamentId: 'tourn-1',
    userId: 'user-phoenix',
    userName: 'Phoenix_FF',
    teamId: 'team-vortex',
    teamName: 'VORTEX ESPORTS',
    ign: 'Phoenix_99',
    playerUid: 'FF-89241031',
    slotNumber: 14,
    registeredAt: '2026-09-02T11:20:00Z',
    status: 'CONFIRMED',
  },
  {
    id: 'reg-2',
    tournamentId: 'tourn-1',
    userId: 'user-soul1',
    userName: 'SoulMortal',
    teamId: 'team-soulfire',
    teamName: 'SOUL FIRE GAMING',
    ign: 'SFG_Mortal',
    playerUid: 'FF-44112233',
    slotNumber: 1,
    registeredAt: '2026-09-02T12:00:00Z',
    status: 'CONFIRMED',
  },
  {
    id: 'reg-3',
    tournamentId: 'tourn-1',
    userId: 'user-god1',
    userName: 'Neyoo_FF',
    teamId: 'team-godlike',
    teamName: 'GODLIKE FF',
    ign: 'GDL_Neyoo',
    playerUid: 'FF-99887766',
    slotNumber: 5,
    registeredAt: '2026-09-03T10:15:00Z',
    status: 'CONFIRMED',
  },
];

export const INITIAL_RESULTS: MatchResult[] = [
  {
    id: 'res-1',
    matchId: 'match-101',
    tournamentId: 'tourn-1',
    teamId: 'team-vortex',
    teamName: 'VORTEX ESPORTS',
    playerUid: 'FF-89241031',
    placement: 1,
    kills: 11,
    placementPoints: 15,
    killPoints: 22,
    bonusPoints: 3,
    penalties: 0,
    totalScore: 40,
    evidenceUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    status: 'UNDER_REVIEW',
    submittedBy: 'user-phoenix',
    submittedByName: 'Phoenix_FF',
    submittedAt: '2026-09-10T18:35:00Z',
    adminNote: 'Screenshot shows clear Booyah and 11 team kills. Ready for admin verification.',
  },
  {
    id: 'res-2',
    matchId: 'match-101',
    tournamentId: 'tourn-1',
    teamId: 'team-soulfire',
    teamName: 'SOUL FIRE GAMING',
    playerUid: 'FF-44112233',
    placement: 2,
    kills: 8,
    placementPoints: 12,
    killPoints: 16,
    bonusPoints: 0,
    penalties: 0,
    totalScore: 28,
    evidenceUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80',
    status: 'VERIFIED',
    submittedBy: 'user-soul1',
    submittedByName: 'SoulMortal',
    submittedAt: '2026-09-10T18:33:00Z',
    verifiedAt: '2026-09-10T18:38:00Z',
    adminNote: 'Placement and kills verified against match lobby telemetry.',
  },
];

export const INITIAL_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    teamOrPlayerName: 'VORTEX ESPORTS',
    teamId: 'team-vortex',
    matches: 1,
    kills: 11,
    placementPoints: 15,
    killPoints: 22,
    bonus: 3,
    penalty: 0,
    totalScore: 40,
  },
  {
    rank: 2,
    teamOrPlayerName: 'SOUL FIRE GAMING',
    teamId: 'team-soulfire',
    matches: 1,
    kills: 8,
    placementPoints: 12,
    killPoints: 16,
    bonus: 0,
    penalty: 0,
    totalScore: 28,
  },
  {
    rank: 3,
    teamOrPlayerName: 'GODLIKE FF',
    teamId: 'team-godlike',
    matches: 1,
    kills: 6,
    placementPoints: 10,
    killPoints: 12,
    bonus: 0,
    penalty: 0,
    totalScore: 22,
  },
  {
    rank: 4,
    teamOrPlayerName: 'HYDRA SQUAD',
    matches: 1,
    kills: 5,
    placementPoints: 8,
    killPoints: 10,
    bonus: 0,
    penalty: 0,
    totalScore: 18,
  },
  {
    rank: 5,
    teamOrPlayerName: 'TOTAL GAMING ELITE',
    matches: 1,
    kills: 3,
    placementPoints: 6,
    killPoints: 6,
    bonus: 0,
    penalty: 0,
    totalScore: 12,
  },
  {
    rank: 6,
    teamOrPlayerName: 'REVENANT ROAR',
    matches: 1,
    kills: 2,
    placementPoints: 5,
    killPoints: 4,
    bonus: 0,
    penalty: 0,
    totalScore: 9,
  },
];

export const INITIAL_WALLET: UserWallet = {
  userId: 'user-phoenix',
  availableBalance: 1250,
  pendingBalance: 200,
  lockedBalance: 0,
  totalDeposited: 3500,
  totalWithdrawn: 2000,
  totalWinnings: 8500,
};

export const INITIAL_LEDGER: WalletLedgerItem[] = [
  {
    id: 'tx-1001',
    userId: 'user-phoenix',
    amount: 1000,
    currency: 'INR',
    type: 'DEPOSIT',
    status: 'COMPLETED',
    reference: 'UPI-REF-9923847102',
    timestamp: '2026-08-15T14:20:00Z',
    balanceBefore: 0,
    balanceAfter: 1000,
    idempotencyKey: 'idem-dep-1001',
  },
  {
    id: 'tx-1002',
    userId: 'user-phoenix',
    amount: 100,
    currency: 'INR',
    type: 'ENTRY_FEE',
    status: 'COMPLETED',
    reference: 'ENTRY-TOURN-BERMUDA-S5',
    timestamp: '2026-08-20T10:10:00Z',
    balanceBefore: 1000,
    balanceAfter: 900,
    idempotencyKey: 'idem-entry-1002',
  },
  {
    id: 'tx-1003',
    userId: 'user-phoenix',
    amount: 2500,
    currency: 'INR',
    type: 'PRIZE',
    status: 'COMPLETED',
    reference: 'PRIZE-1ST-PLACE-ALPINE-S5',
    timestamp: '2026-08-28T23:05:00Z',
    balanceBefore: 900,
    balanceAfter: 3400,
    idempotencyKey: 'idem-prize-1003',
  },
  {
    id: 'tx-1004',
    userId: 'user-phoenix',
    amount: 2000,
    currency: 'INR',
    type: 'WITHDRAWAL',
    status: 'COMPLETED',
    reference: 'WDR-UPI-rohan@okhdfcbank',
    timestamp: '2026-08-30T11:00:00Z',
    balanceBefore: 3400,
    balanceAfter: 1400,
    idempotencyKey: 'idem-wdr-1004',
  },
  {
    id: 'tx-1005',
    userId: 'user-phoenix',
    amount: 50,
    currency: 'INR',
    type: 'ENTRY_FEE',
    status: 'COMPLETED',
    reference: 'ENTRY-BATTLE-ARENA-S6',
    timestamp: '2026-09-02T11:20:00Z',
    balanceBefore: 1400,
    balanceAfter: 1350,
    idempotencyKey: 'idem-entry-1005',
  },
  {
    id: 'tx-1006',
    userId: 'user-phoenix',
    amount: 100,
    currency: 'INR',
    type: 'ENTRY_FEE',
    status: 'COMPLETED',
    reference: 'ENTRY-BERMUDA-PRO-S6',
    timestamp: '2026-09-06T15:30:00Z',
    balanceBefore: 1350,
    balanceAfter: 1250,
    idempotencyKey: 'idem-entry-1006',
  },
];

export const INITIAL_WITHDRAWALS: WithdrawalRequest[] = [
  {
    id: 'wdr-201',
    userId: 'user-phoenix',
    userName: 'Phoenix_FF',
    amount: 200,
    method: 'UPI',
    accountDetails: 'rohan.sharma@okhdfcbank',
    processingFee: 0,
    finalAmount: 200,
    status: 'PENDING',
    requestDate: '2026-09-09T17:40:00Z',
  },
  {
    id: 'wdr-199',
    userId: 'user-phoenix',
    userName: 'Phoenix_FF',
    amount: 2000,
    method: 'UPI',
    accountDetails: 'rohan.sharma@okhdfcbank',
    processingFee: 0,
    finalAmount: 2000,
    status: 'PAID',
    requestDate: '2026-08-30T10:00:00Z',
    processingDate: '2026-08-30T11:00:00Z',
    adminNote: 'Processed successfully via UPI payout gateway.',
  },
  {
    id: 'wdr-200',
    userId: 'user-soul1',
    userName: 'SoulMortal',
    amount: 5000,
    method: 'BANK_TRANSFER',
    accountDetails: 'HDFC0001234 - 50100492817293',
    processingFee: 25,
    finalAmount: 4975,
    status: 'APPROVED',
    requestDate: '2026-09-08T14:10:00Z',
    processingDate: '2026-09-09T09:30:00Z',
    adminNote: 'KYC verified. Queued for batch settlement.',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'user-phoenix',
    title: 'Match Room Released!',
    message: 'Room ID & Password for Free Fire Battle Arena Match #1 are now available. Copy credentials and enter room.',
    type: 'MATCH',
    read: false,
    timestamp: '2026-09-10T17:45:00Z',
    link: '/match-room',
  },
  {
    id: 'notif-2',
    userId: 'user-phoenix',
    title: 'Registration Confirmed',
    message: 'Team VORTEX ESPORTS confirmed for Bermuda Clash Pro Championship.',
    type: 'TOURNAMENT',
    read: true,
    timestamp: '2026-09-06T15:30:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-phoenix',
    title: 'Prize Credited — ₹2,500',
    message: 'Congratulations! Your 1st place prize for Alpine Pro Scrims S5 has been credited to your wallet.',
    type: 'WALLET',
    read: true,
    timestamp: '2026-08-28T23:05:00Z',
  },
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'ticket-501',
    userId: 'user-phoenix',
    userName: 'Phoenix_FF',
    category: 'RESULT',
    subject: 'Match 1 kill count discrepancy inquiry',
    status: 'IN_PROGRESS',
    createdAt: '2026-09-10T18:40:00Z',
    updatedAt: '2026-09-10T18:45:00Z',
    messages: [
      {
        id: 'msg-1',
        sender: 'USER',
        senderName: 'Phoenix_FF',
        message: 'Hello admin team, we finished 1st with 11 team kills in Match 1. Screenshot is uploaded. Just confirming our squad roster points.',
        timestamp: '2026-09-10T18:40:00Z',
      },
      {
        id: 'msg-2',
        sender: 'ADMIN',
        senderName: 'Support Agent - Sarah',
        message: 'Hi Phoenix, we reviewed your uploaded end-screen screenshot. It matches the kill feed logs. Your score of 40 points is queued for immediate verification.',
        timestamp: '2026-09-10T18:45:00Z',
      },
    ],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    actor: 'Apex_Operator',
    actorRole: 'SUPER_ADMIN',
    action: 'TOURNAMENT_CREATED',
    entity: 'Tournament',
    entityId: 'tourn-1',
    metadata: { name: 'FREE FIRE BATTLE ARENA — S6', prizePool: 10000, entryFee: 50 },
    ip: '103.21.144.92',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    timestamp: '2026-08-25T10:00:00Z',
  },
  {
    id: 'audit-2',
    actor: 'Apex_Operator',
    actorRole: 'SUPER_ADMIN',
    action: 'ROOM_CREDENTIALS_RELEASED',
    entity: 'Match',
    entityId: 'match-101',
    metadata: { roomId: '6582049', matchNumber: 1 },
    ip: '103.21.144.92',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    timestamp: '2026-09-10T17:45:00Z',
  },
  {
    id: 'audit-3',
    actor: 'FinanceManager_Karan',
    actorRole: 'FINANCE_MANAGER',
    action: 'WITHDRAWAL_APPROVED',
    entity: 'WithdrawalRequest',
    entityId: 'wdr-200',
    metadata: { amount: 5000, user: 'SoulMortal', bank: 'HDFC' },
    ip: '49.36.128.5',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    timestamp: '2026-09-09T09:30:00Z',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  platformFeePercent: 10,
  minDeposit: 50,
  maxDeposit: 50000,
  minWithdrawal: 100,
  maxWithdrawal: 25000,
  maintenanceMode: false,
  antiCheatNotice: 'All gameplay is continuously monitored via anti-cheat hash integrity. Third-party injectors, modified APKs, or macro scripts will lead to permanent hardware and UID ban.',
  roomAutoReleaseMins: 15,
};
